### PR TITLE
Redesign build to gradle

### PR DESCRIPTION
**Pull request by sea-kg**
Just building from command line

### CODE REVIEW

**Comment by JustGregory** [comment]
Technically, it's allowable to ```gitignore``` the gradlew files too, as that's something the user can and should generate from the command-line or IDE.

**Comment by sea-kg** [comment]
1. gradle/* and gradlew - generated by `gradle init`
2. gradle/* and gradlew - it's need if gradle not installed in system
3. gradle/* and gradlew - gradlew will be download gradle expected version
(gradle/*.jar  is little and only for init download)
4. In the system can be installed gradle 2.1 but for build need 2.5 and in
this case user must run gradlew (for compatibility)



Best regards
Evgenii Sopov
https://github.com/sea-kg/
other e-mails: sea-kg@ya.ru
skype: sea-kg

2016-07-22 16:08 GMT+07:00 Gregory <notifications@github.com>:

**Comment by ForsakenHarmony** [comment]
```
Unofficial mirror of FernFlower Java decompiler (All pulls should be submitted upstream) - https://github.com/JetBrains/intellij-community/tree/master/plugins/java-decompiler/engine
```

**Comment by DMP9-MC** [comment]
You will need to create a pull request on the [IntelliJ Community](https://github.com/jetbrains/intellij-community) repository. This repository will automatically be updated when changes to the [java-decompiler](https://github.com/JetBrains/intellij-community/tree/master/plugins/java-decompiler/engine) (fernflower) occur.

**Comment by markjfisher** [comment]
In the mean time, the following is a simplified gradle script that will build the application with the directories as they are, leaving the jar in build/libs/fernflower.jar:

```
apply plugin: 'java'

repositories {
  mavenCentral()
}

dependencies {
  testCompile 'junit:junit:4.12'
  testCompile group: 'org.assertj', name: 'assertj-core', version: '3.6.2'
}

sourceSets {
  main {
    java.srcDirs = ['src']
  }
  test {
    java.srcDirs = ['test']
  }
}

jar {
    manifest {
        attributes 'Main-Class': 'org.jetbrains.java.decompiler.main.decompiler.ConsoleDecompiler'
    }
}
```

**Pull request closed without merging**
